# Generated by Django 4.2.2 on 2023-06-22 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employeapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Designation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AsignDesignation', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Createteam', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EmployeeID', models.CharField(default=None, max_length=60, null=True, unique=True)),
                ('Firstname', models.CharField(max_length=60, null=True)),
                ('Lastname', models.CharField(max_length=60, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('salary', models.IntegerField()),
                ('phonenumber', models.IntegerField()),
                ('designation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='employeapp.designation')),
                ('team', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='employeapp.team')),
            ],
        ),
    ]
