# Generated by Django 4.2.2 on 2023-06-23 03:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employeapp', '0002_designation_team_employeemodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='leavetype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ltype', models.CharField(max_length=60)),
            ],
        ),
        migrations.AlterField(
            model_name='designation',
            name='AsignDesignation',
            field=models.CharField(max_length=60, unique=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='Createteam',
            field=models.CharField(max_length=60, unique=True),
        ),
        migrations.CreateModel(
            name='leave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fromm', models.DateField()),
                ('to', models.DateField()),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employeapp.leavetype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employeapp.employeemodel')),
            ],
        ),
    ]
