# Generated by Django 4.2.2 on 2023-06-23 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeapp', '0003_leavetype_alter_designation_asigndesignation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='designation',
            name='AsignDesignation',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='team',
            name='Createteam',
            field=models.CharField(max_length=60),
        ),
    ]
