# Generated by Django 4.2.2 on 2023-06-23 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeapp', '0004_alter_designation_asigndesignation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeemodel',
            name='EmployeeID',
            field=models.CharField(default=None, max_length=60, null=True),
        ),
    ]
