# Generated by Django 4.2.2 on 2023-06-23 06:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employeapp', '0005_alter_employeemodel_employeeid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeemodel',
            name='designation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employeapp.designation'),
        ),
        migrations.AlterField(
            model_name='employeemodel',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employeapp.team'),
        ),
    ]
